/** Declaration file generated by dts-gen */

declare function humanize_duration(ms: any, humanizerOptions: any): any;
declare namespace humanize_duration {
    const conjunction: string;
    const delimiter: string;
    const language: string;
    const languages: {
    };
    const round: boolean;
    const serialComma: boolean;
    const spacer: string;
    const unitMeasures: {
        d: number;
        h: number;
        m: number;
        mo: number;
        ms: number;
        s: number;
        w: number;
        y: number;
    };
    const units: string[];
    function getSupportedLanguages(): any;
    function humanizer(passedOptions: any): any;
}
export = humanize_duration;